# 예시
start:
  name: "시작지점"
  x: 0.540846049785614
  y: -0.4997600317001343
  yaw: 0.0

destinations:
  - name: "2층 강의실 과자코너"
    x: 7.480587959289551
    y: -0.963249921798706
    yaw: 0.0
  - name: "2층 강의실 생필품 코너"
    x: 6.596812725067139
    y: -3.0922837257385254
    yaw: 0.0
